# Site settings
title: Telekom Security
description: "Telekom Security research and publications"
url: "https://github.security.telekom.com"
author:
  name: "Telekom Security"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:year/:month/:title.html
paginate: 8
paginate_path: /page:num/

excerpt_separator: <!--more-->

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
navigation_menu: false
theme: jekyll-theme-slate
